apiVersion: v2
name: api
description: Helm chart for raidcontrol-backend
type: application
version: 0.0.0

dependencies:
  - name: generic-app
    version: 2.1.7
    repository: https://moreirodamian.github.io/helm-charts/
