generic-app:
    region: nyc1

    hpa:
        minReplicas: 1
        maxReplicas: 5
        cpuPercentage: 80

    revisionHistoryLimit: 1

    rollout: ~

    dockerSecret:
        encryptedData:
            .dockerconfigjson: AgAQGXFurSaskBuReSHFivuSx7KuMjH3rt5xejyyqFYSTcfJhWPIznGSZYSOLakWbVzVoqJ7upm6wFXiNScuyBIKgh6OIZn7jcmLn4fi02sJIL6KHri1T3wNKDaaI3Uq73swpK+gJpTpNC3zkii2Gs6HA478Gt+hyR/onQrREPrcmLUVOCho7iaW+qw+/GLfi2O8opi5ageKNLmSQSNDvdasbhb0TjaMyslM48Mm3SaAoGAxPXA6nKEdC1qaAABNCCYn4K9malHIGIbjYPc1Iijj6GVSJ0H6A7IJJIsV6q7yRABBnTDr67aQV0QziW6qwGVxuXOOHjWAfydsaz4N9rD3YlR/my1uCWyYWXtQHPSjpBXULJg41w/578WdvpE+sRGNQ3KAsC9Uk1Da0bRmLzazUezANGjtKAFjpHRtvawv8mi7h+sdvdJf8+J7KR808wj4sFyIHgEv2+Tqtun2QFstkAgzARdIr/waCK/gx4/2PMLLyPL/fsXncIezgLQ1u6BpWcGnAfkSTx5NSod3RrdY6YEQZPiTnJlPT6WSWvZnpema4GBeYa8pBYcQSEKpL2YI2YSCy/QWv35Ab3H9Fa/cpRzR3dPVvccVJ9ioX6T7IrLWJmiE0E7HpH56HM17ewNaK0Ps0PGjFAWFcKxvMtHucHROi0t8oHlwwC6m+eLevSb8tLz9sduJD97mt8ZfOY4gXLcvyAcCX1t47NC8Qr2ijNb0pr+9kIVzwBsnAIQbbX9oR+qJDMmtDn9bAuYyo+sfO8CEO0GD36xyOTaNtcVYk17LPcLG/FoIuNmPoOXKS+juyhTHsuhwftjlxHAGO+MqnJMSJ5xI9pI4lWQ6ktkXRtvEYvm1SUVYEld/nPOVYbK/XhaCEdupgX7yTA6wi9HJQf0PhbNmm7GVt7u5PQKSBLAAWZ3gJqNsnh7gx97GyhPfhlzZrQo1Q4Cmj+pMFKf7JsGr2kU2YIyQKTgwgwlECO4Uhvg=
    app:
        image:
            registry: registry.hub.docker.com/kodearsrl
            name: raidcontrol_backend
            tag: "0.0.1"
        ports:
            - name: http
              containerPort: 8000
              protocol: TCP
        livenessProbe:
            httpGet:
                path: /health
                port: http
        readinessProbe:
            httpGet:
                path: /health
                port: http
        startupProbe:
            httpGet:
                path: /health
                port: http
                scheme: HTTP
            failureThreshold: 30
            periodSeconds: 2

    service:
        create: true
        grpc: false
        type: ClusterIP
        port: 8000
        targetPort: 8000

    sealedSecrets:
        enabled: true
        type: Opaque
        annotations:
            helm.sh/hook-weight: "-5"
            sealedsecrets.bitnami.com/cluster-wide: "true"

    ingress:
        create: true
        grpc: false
        letsencrypt: true
        annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
            nginx.ingress.kubernetes.io/affinity: "cookie"
            nginx.ingress.kubernetes.io/affinity-mode: "persistent"
            nginx.ingress.kubernetes.io/session-cookie-name: "SERVERID"
            nginx.ingress.kubernetes.io/session-cookie-path: "/"
            nginx.ingress.kubernetes.io/session-cookie-max-age: "86400"
